#############################################################################
# Makefile for building: ImagePlay
# Generated by qmake (3.0) (Qt 5.4.0)
# Project:  ImagePlay.pro
# Template: subdirs
# Command: C:\Qt\5.4\msvc2013_64\bin\qmake.exe -spec win32-msvc2013 -o Makefile ImagePlay.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = C:\Qt\5.4\msvc2013_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = copy /y
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-ImagePlay \
		sub-IPL


sub-ImagePlay-qmake_all:  FORCE
	@if not exist ImagePlay\ mkdir ImagePlay\ & if not exist ImagePlay\ exit 1
	cd ImagePlay\ && $(QMAKE) D:\Projects\imageplay\ImagePlay\ImagePlay.pro -spec win32-msvc2013 -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ImagePlay\ && $(MAKE) -f Makefile qmake_all
sub-ImagePlay: sub-IPL FORCE
	@if not exist ImagePlay\ mkdir ImagePlay\ & if not exist ImagePlay\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ImagePlay\ && ( if not exist Makefile $(QMAKE) D:\Projects\imageplay\ImagePlay\ImagePlay.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile
sub-ImagePlay-make_first-ordered: FORCE
	@if not exist ImagePlay\ mkdir ImagePlay\ & if not exist ImagePlay\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ImagePlay\ && ( if not exist Makefile $(QMAKE) D:\Projects\imageplay\ImagePlay\ImagePlay.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile 
sub-ImagePlay-make_first: sub-IPL-make_first FORCE
	@if not exist ImagePlay\ mkdir ImagePlay\ & if not exist ImagePlay\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ImagePlay\ && ( if not exist Makefile $(QMAKE) D:\Projects\imageplay\ImagePlay\ImagePlay.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile 
sub-ImagePlay-all-ordered: FORCE
	@if not exist ImagePlay\ mkdir ImagePlay\ & if not exist ImagePlay\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ImagePlay\ && ( if not exist Makefile $(QMAKE) D:\Projects\imageplay\ImagePlay\ImagePlay.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile all
sub-ImagePlay-all: sub-IPL-all FORCE
	@if not exist ImagePlay\ mkdir ImagePlay\ & if not exist ImagePlay\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ImagePlay\ && ( if not exist Makefile $(QMAKE) D:\Projects\imageplay\ImagePlay\ImagePlay.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile all
sub-ImagePlay-clean-ordered: FORCE
	@if not exist ImagePlay\ mkdir ImagePlay\ & if not exist ImagePlay\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ImagePlay\ && ( if not exist Makefile $(QMAKE) D:\Projects\imageplay\ImagePlay\ImagePlay.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile clean
sub-ImagePlay-clean: sub-IPL-clean FORCE
	@if not exist ImagePlay\ mkdir ImagePlay\ & if not exist ImagePlay\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ImagePlay\ && ( if not exist Makefile $(QMAKE) D:\Projects\imageplay\ImagePlay\ImagePlay.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile clean
sub-ImagePlay-distclean-ordered: FORCE
	@if not exist ImagePlay\ mkdir ImagePlay\ & if not exist ImagePlay\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ImagePlay\ && ( if not exist Makefile $(QMAKE) D:\Projects\imageplay\ImagePlay\ImagePlay.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-ImagePlay-distclean: sub-IPL-distclean FORCE
	@if not exist ImagePlay\ mkdir ImagePlay\ & if not exist ImagePlay\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ImagePlay\ && ( if not exist Makefile $(QMAKE) D:\Projects\imageplay\ImagePlay\ImagePlay.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-ImagePlay-install_subtargets-ordered: FORCE
	@if not exist ImagePlay\ mkdir ImagePlay\ & if not exist ImagePlay\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ImagePlay\ && ( if not exist Makefile $(QMAKE) D:\Projects\imageplay\ImagePlay\ImagePlay.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile install
sub-ImagePlay-install_subtargets: sub-IPL-install_subtargets FORCE
	@if not exist ImagePlay\ mkdir ImagePlay\ & if not exist ImagePlay\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ImagePlay\ && ( if not exist Makefile $(QMAKE) D:\Projects\imageplay\ImagePlay\ImagePlay.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile install
sub-ImagePlay-uninstall_subtargets-ordered: FORCE
	@if not exist ImagePlay\ mkdir ImagePlay\ & if not exist ImagePlay\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ImagePlay\ && ( if not exist Makefile $(QMAKE) D:\Projects\imageplay\ImagePlay\ImagePlay.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-ImagePlay-uninstall_subtargets: sub-IPL-uninstall_subtargets FORCE
	@if not exist ImagePlay\ mkdir ImagePlay\ & if not exist ImagePlay\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ImagePlay\ && ( if not exist Makefile $(QMAKE) D:\Projects\imageplay\ImagePlay\ImagePlay.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-IPL-qmake_all: sub-ImagePlay-qmake_all FORCE
	@if not exist IPL\ mkdir IPL\ & if not exist IPL\ exit 1
	cd IPL\ && $(QMAKE) D:\Projects\imageplay\IPL\IPL.pro -spec win32-msvc2013 -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IPL\ && $(MAKE) -f Makefile qmake_all
sub-IPL: FORCE
	@if not exist IPL\ mkdir IPL\ & if not exist IPL\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IPL\ && ( if not exist Makefile $(QMAKE) D:\Projects\imageplay\IPL\IPL.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile
sub-IPL-make_first-ordered: sub-ImagePlay-make_first-ordered  FORCE
	@if not exist IPL\ mkdir IPL\ & if not exist IPL\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IPL\ && ( if not exist Makefile $(QMAKE) D:\Projects\imageplay\IPL\IPL.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile 
sub-IPL-make_first: FORCE
	@if not exist IPL\ mkdir IPL\ & if not exist IPL\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IPL\ && ( if not exist Makefile $(QMAKE) D:\Projects\imageplay\IPL\IPL.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile 
sub-IPL-all-ordered: sub-ImagePlay-all-ordered  FORCE
	@if not exist IPL\ mkdir IPL\ & if not exist IPL\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IPL\ && ( if not exist Makefile $(QMAKE) D:\Projects\imageplay\IPL\IPL.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile all
sub-IPL-all: FORCE
	@if not exist IPL\ mkdir IPL\ & if not exist IPL\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IPL\ && ( if not exist Makefile $(QMAKE) D:\Projects\imageplay\IPL\IPL.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile all
sub-IPL-clean-ordered: sub-ImagePlay-clean-ordered  FORCE
	@if not exist IPL\ mkdir IPL\ & if not exist IPL\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IPL\ && ( if not exist Makefile $(QMAKE) D:\Projects\imageplay\IPL\IPL.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile clean
sub-IPL-clean: FORCE
	@if not exist IPL\ mkdir IPL\ & if not exist IPL\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IPL\ && ( if not exist Makefile $(QMAKE) D:\Projects\imageplay\IPL\IPL.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile clean
sub-IPL-distclean-ordered: sub-ImagePlay-distclean-ordered  FORCE
	@if not exist IPL\ mkdir IPL\ & if not exist IPL\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IPL\ && ( if not exist Makefile $(QMAKE) D:\Projects\imageplay\IPL\IPL.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-IPL-distclean: FORCE
	@if not exist IPL\ mkdir IPL\ & if not exist IPL\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IPL\ && ( if not exist Makefile $(QMAKE) D:\Projects\imageplay\IPL\IPL.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-IPL-install_subtargets-ordered: sub-ImagePlay-install_subtargets-ordered  FORCE
	@if not exist IPL\ mkdir IPL\ & if not exist IPL\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IPL\ && ( if not exist Makefile $(QMAKE) D:\Projects\imageplay\IPL\IPL.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile install
sub-IPL-install_subtargets: FORCE
	@if not exist IPL\ mkdir IPL\ & if not exist IPL\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IPL\ && ( if not exist Makefile $(QMAKE) D:\Projects\imageplay\IPL\IPL.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile install
sub-IPL-uninstall_subtargets-ordered: sub-ImagePlay-uninstall_subtargets-ordered  FORCE
	@if not exist IPL\ mkdir IPL\ & if not exist IPL\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IPL\ && ( if not exist Makefile $(QMAKE) D:\Projects\imageplay\IPL\IPL.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-IPL-uninstall_subtargets: FORCE
	@if not exist IPL\ mkdir IPL\ & if not exist IPL\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IPL\ && ( if not exist Makefile $(QMAKE) D:\Projects\imageplay\IPL\IPL.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: ImagePlay.pro C:\Qt\5.4\msvc2013_64\mkspecs\win32-msvc2013\qmake.conf C:\Qt\5.4\msvc2013_64\mkspecs\features\spec_pre.prf \
		C:\Qt\5.4\msvc2013_64\mkspecs\common\shell-win32.conf \
		C:\Qt\5.4\msvc2013_64\mkspecs\qconfig.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_axbase.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_axbase_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_axcontainer.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_axcontainer_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_axserver.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_axserver_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_bluetooth.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_bluetooth_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_bootstrap_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_clucene_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_concurrent.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_concurrent_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_core.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_core_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_declarative.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_declarative_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_designer.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_designer_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_designercomponents_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_enginio.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_enginio_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_gui.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_gui_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_help.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_help_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_location.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_location_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_multimedia.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_multimedia_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_multimediawidgets.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_network.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_network_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_nfc.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_nfc_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_opengl.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_opengl_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_openglextensions.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_openglextensions_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_platformsupport_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_positioning.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_positioning_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_printsupport.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_printsupport_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_qml.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_qml_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_qmltest.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_qmltest_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_quick.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_quick_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_quickparticles_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_quickwidgets.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_script.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_script_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_scripttools.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_scripttools_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_sensors.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_sensors_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_serialport.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_serialport_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_sql.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_sql_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_svg.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_svg_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_testlib.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_testlib_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_uitools.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_uitools_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_webchannel.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_webchannel_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_webengine.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_webengine_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_webenginecore.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_webenginecore_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_webenginewidgets.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_webkit.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_webkit_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_webkitwidgets.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_webkitwidgets_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_websockets.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_websockets_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_webview.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_webview_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_widgets.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_widgets_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_winextras.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_winextras_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_xml.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_xml_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_xmlpatterns.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		C:\Qt\5.4\msvc2013_64\mkspecs\features\qt_functions.prf \
		C:\Qt\5.4\msvc2013_64\mkspecs\features\qt_config.prf \
		C:\Qt\5.4\msvc2013_64\mkspecs\features\win32\qt_config.prf \
		C:\Qt\5.4\msvc2013_64\mkspecs\win32-msvc2013\qmake.conf \
		C:\Qt\5.4\msvc2013_64\mkspecs\features\spec_post.prf \
		C:\Qt\5.4\msvc2013_64\mkspecs\features\exclusive_builds.prf \
		C:\Qt\5.4\msvc2013_64\mkspecs\features\default_pre.prf \
		C:\Qt\5.4\msvc2013_64\mkspecs\features\win32\default_pre.prf \
		C:\Qt\5.4\msvc2013_64\mkspecs\features\resolve_config.prf \
		C:\Qt\5.4\msvc2013_64\mkspecs\features\exclusive_builds_post.prf \
		C:\Qt\5.4\msvc2013_64\mkspecs\features\default_post.prf \
		C:\Qt\5.4\msvc2013_64\mkspecs\features\win32\rtti.prf \
		C:\Qt\5.4\msvc2013_64\mkspecs\features\precompile_header.prf \
		C:\Qt\5.4\msvc2013_64\mkspecs\features\warn_on.prf \
		C:\Qt\5.4\msvc2013_64\mkspecs\features\win32\windows.prf \
		C:\Qt\5.4\msvc2013_64\mkspecs\features\testcase_targets.prf \
		C:\Qt\5.4\msvc2013_64\mkspecs\features\exceptions.prf \
		C:\Qt\5.4\msvc2013_64\mkspecs\features\yacc.prf \
		C:\Qt\5.4\msvc2013_64\mkspecs\features\lex.prf \
		ImagePlay.pro
	$(QMAKE) -spec win32-msvc2013 -o Makefile ImagePlay.pro
C:\Qt\5.4\msvc2013_64\mkspecs\features\spec_pre.prf:
C:\Qt\5.4\msvc2013_64\mkspecs\common\shell-win32.conf:
C:\Qt\5.4\msvc2013_64\mkspecs\qconfig.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_axbase.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_axbase_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_axcontainer.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_axcontainer_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_axserver.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_axserver_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_bluetooth.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_bluetooth_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_bootstrap_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_clucene_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_concurrent.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_concurrent_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_core.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_core_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_declarative.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_declarative_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_designer.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_designer_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_designercomponents_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_enginio.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_enginio_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_gui.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_gui_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_help.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_help_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_location.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_location_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_multimedia.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_multimedia_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_multimediawidgets.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_network.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_network_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_nfc.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_nfc_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_opengl.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_opengl_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_openglextensions.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_openglextensions_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_platformsupport_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_positioning.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_positioning_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_printsupport.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_printsupport_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_qml.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_qml_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_qmldevtools_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_qmltest.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_qmltest_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_quick.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_quick_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_quickparticles_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_quickwidgets.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_quickwidgets_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_script.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_script_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_scripttools.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_scripttools_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_sensors.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_sensors_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_serialport.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_serialport_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_sql.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_sql_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_svg.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_svg_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_testlib.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_testlib_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_uitools.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_uitools_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_webchannel.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_webchannel_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_webengine.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_webengine_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_webenginecore.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_webenginecore_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_webenginewidgets.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_webkit.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_webkit_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_webkitwidgets.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_webkitwidgets_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_websockets.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_websockets_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_webview.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_webview_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_widgets.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_widgets_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_winextras.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_winextras_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_xml.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_xml_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_xmlpatterns.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
C:\Qt\5.4\msvc2013_64\mkspecs\features\qt_functions.prf:
C:\Qt\5.4\msvc2013_64\mkspecs\features\qt_config.prf:
C:\Qt\5.4\msvc2013_64\mkspecs\features\win32\qt_config.prf:
C:\Qt\5.4\msvc2013_64\mkspecs\win32-msvc2013\qmake.conf:
C:\Qt\5.4\msvc2013_64\mkspecs\features\spec_post.prf:
C:\Qt\5.4\msvc2013_64\mkspecs\features\exclusive_builds.prf:
C:\Qt\5.4\msvc2013_64\mkspecs\features\default_pre.prf:
C:\Qt\5.4\msvc2013_64\mkspecs\features\win32\default_pre.prf:
C:\Qt\5.4\msvc2013_64\mkspecs\features\resolve_config.prf:
C:\Qt\5.4\msvc2013_64\mkspecs\features\exclusive_builds_post.prf:
C:\Qt\5.4\msvc2013_64\mkspecs\features\default_post.prf:
C:\Qt\5.4\msvc2013_64\mkspecs\features\win32\rtti.prf:
C:\Qt\5.4\msvc2013_64\mkspecs\features\precompile_header.prf:
C:\Qt\5.4\msvc2013_64\mkspecs\features\warn_on.prf:
C:\Qt\5.4\msvc2013_64\mkspecs\features\win32\windows.prf:
C:\Qt\5.4\msvc2013_64\mkspecs\features\testcase_targets.prf:
C:\Qt\5.4\msvc2013_64\mkspecs\features\exceptions.prf:
C:\Qt\5.4\msvc2013_64\mkspecs\features\yacc.prf:
C:\Qt\5.4\msvc2013_64\mkspecs\features\lex.prf:
ImagePlay.pro:
qmake: FORCE
	@$(QMAKE) -spec win32-msvc2013 -o Makefile ImagePlay.pro

qmake_all: sub-ImagePlay-qmake_all sub-IPL-qmake_all FORCE

make_first: sub-ImagePlay-make_first-ordered sub-IPL-make_first-ordered FORCE
all: sub-ImagePlay-all-ordered sub-IPL-all-ordered FORCE
clean: sub-ImagePlay-clean-ordered sub-IPL-clean-ordered FORCE
distclean: sub-ImagePlay-distclean-ordered sub-IPL-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-ImagePlay-install_subtargets-ordered sub-IPL-install_subtargets-ordered FORCE
uninstall_subtargets: sub-ImagePlay-uninstall_subtargets-ordered sub-IPL-uninstall_subtargets-ordered FORCE

sub-ImagePlay-debug_ordered:
	@if not exist ImagePlay\ mkdir ImagePlay\ & if not exist ImagePlay\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ImagePlay\ && ( if not exist Makefile $(QMAKE) D:\Projects\imageplay\ImagePlay\ImagePlay.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile debug
sub-IPL-debug_ordered: sub-ImagePlay-debug_ordered 
	@if not exist IPL\ mkdir IPL\ & if not exist IPL\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IPL\ && ( if not exist Makefile $(QMAKE) D:\Projects\imageplay\IPL\IPL.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-ImagePlay-debug_ordered sub-IPL-debug_ordered

sub-ImagePlay-release_ordered:
	@if not exist ImagePlay\ mkdir ImagePlay\ & if not exist ImagePlay\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ImagePlay\ && ( if not exist Makefile $(QMAKE) D:\Projects\imageplay\ImagePlay\ImagePlay.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile release
sub-IPL-release_ordered: sub-ImagePlay-release_ordered 
	@if not exist IPL\ mkdir IPL\ & if not exist IPL\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IPL\ && ( if not exist Makefile $(QMAKE) D:\Projects\imageplay\IPL\IPL.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile release
release: sub-ImagePlay-release_ordered sub-IPL-release_ordered

sub-ImagePlay-check_ordered:
	@if not exist ImagePlay\ mkdir ImagePlay\ & if not exist ImagePlay\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd ImagePlay\ && ( if not exist Makefile $(QMAKE) D:\Projects\imageplay\ImagePlay\ImagePlay.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile check
sub-IPL-check_ordered: sub-ImagePlay-check_ordered 
	@if not exist IPL\ mkdir IPL\ & if not exist IPL\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd IPL\ && ( if not exist Makefile $(QMAKE) D:\Projects\imageplay\IPL\IPL.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile check
check: sub-ImagePlay-check_ordered sub-IPL-check_ordered
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

