#include <QApplication>
#include <QStyleFactory>
#include <QMessageBox>
#include <QSplashScreen>
#include <QThread>
#include <QMainWindow>
#include <QLabel>
#include <QMessageBox>
#include <QMenuBar>
#include <QMouseEvent>
#include <QGraphicsScene>
#include <QGraphicsView>
#include <QDir>
#include <QFormLayout>
#include <QSpinBox>
#include <QSettings>
#include <QMutableListIterator>
#include <QPluginLoader>
